.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.31.0 */

glabel func_81200000
    /* 07F980 81200000 08480008 */  j           func_81200020
    /* 07F984 81200004 00000000 */   nop

glabel D_81200008
    /* 07F988 81200008 46524147 */ .word 0x46524147 /* invalid instruction */
    /* 07F98C 8120000C 4D454E54 */ .word 0x4D454E54 /* invalid instruction */
    /* 07F990 81200010 00000020 */ .word 0x00000020
    /* 07F994 81200014 0002B1E0 */ .word 0x0002B1E0 /* invalid instruction */
    /* 07F998 81200018 0002E300 */ .word 0x0002E300
    /* 07F99C 8120001C 00034710 */ .word 0x00034710 /* invalid instruction */
