.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.31.0 */

glabel abs_asm
    /* 00C4A0 8000B8A0 03E00008 */  jr          $ra
    /* 00C4A4 8000B8A4 46006005 */   abs.s      $fv0, $fa0
    /* 00C4A8 8000B8A8 00000000 */  nop
    /* 00C4AC 8000B8AC 00000000 */  nop
