.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.31.0 */

/* Handwritten function */
glabel entry_point
    /* 001000 80000400 3C088008 */  lui         $t0, %hi(text_bss_VRAM)
    /* 001004 80000404 3C090008 */  lui         $t1, (0x85E30 >> 16)
    /* 001008 80000408 2508ED80 */  addiu       $t0, $t0, %lo(text_bss_VRAM)
    /* 00100C 8000040C 35295E30 */  ori         $t1, $t1, (0x85E30 & 0xFFFF)
  .L80000410:
    /* 001010 80000410 2129FFF8 */  addi        $t1, $t1, -0x8 /* handwritten instruction */
    /* 001014 80000414 AD000000 */  sw          $zero, 0x0($t0)
    /* 001018 80000418 AD000004 */  sw          $zero, 0x4($t0)
    /* 00101C 8000041C 1520FFFC */  bnez        $t1, .L80000410
    /* 001020 80000420 21080008 */   addi       $t0, $t0, 0x8 /* handwritten instruction */
    /* 001024 80000424 3C0A8000 */  lui         $t2, %hi(Main)
    /* 001028 80000428 3C1D8008 */  lui         $sp, %hi(D_8007F180)
    /* 00102C 8000042C 254A0530 */  addiu       $t2, $t2, %lo(Main)
    /* 001030 80000430 01400008 */  jr          $t2
    /* 001034 80000434 27BDF180 */   addiu      $sp, $sp, %lo(D_8007F180)
    /* 001038 80000438 00000000 */  nop
    /* 00103C 8000043C 00000000 */  nop
    /* 001040 80000440 00000000 */  nop
    /* 001044 80000444 00000000 */  nop
    /* 001048 80000448 00000000 */  nop
    /* 00104C 8000044C 00000000 */  nop
    /* 001050 80000450 00000000 */  nop
    /* 001054 80000454 00000000 */  nop
    /* 001058 80000458 00000000 */  nop
    /* 00105C 8000045C 00000000 */  nop
